const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORGANIZER_OWNER: 'ORGANIZER_OWNER',
  ORGANIZER_ADMIN: 'ORGANIZER_ADMIN',
  EVENT_MANAGER: 'EVENT_MANAGER',
  TICKET_VERIFIER: 'TICKET_VERIFIER',
  CUSTOMER: 'CUSTOMER',
});

module.exports = {
  ROLES,
};
